### ISSUE TITLE
Could not find module 'shcore

### ISSUE THREAD

**Issue by t1nyX** [Akascape/CTkColorPicker#5]
Traceback (most recent call last):
  File "d:\Programming\test.py", line 2, in <module>
    from CTkColorPicker import AskColor 
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\CTkColorPicker\__init__.py", line 10, in <module>
    from .ctk_color_picker import AskColor
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\CTkColorPicker\ctk_color_picker.py", line 14, in <module>
    ctypes.windll.shcore.SetProcessDpiAwareness(0)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'shcore' (or one of its dependencies). Try using the full path with constructor syntax.

How to fix it?

**Comment by Akascape** [comment]
@t1nyX 
I guess this is version problem. In python v3.8, the *.dll* search mechanism was changed. 
Try updating python to the latest version.

If problem persists, then remove line `#14` from the code.

**Comment by Akascape** [comment]
@t1nyX 
It should be fixed by now, also added a new parameter: `width` to adjust the window size.
